name: "[prod] Test and publish the image on commit to main"

on:
  push:
    branches: main

jobs:

  build-container:
    runs-on: self-hosted
    environment: 'dev'
    steps:
    - name: "[build-container] Checkout code"
      uses: actions/checkout@v2
    - name: "[build-container] Build the container locally"
      run: docker build -t homekit-monitord:prod .
    - name: "[build-container] Run the container locally"
      run: docker run --name homekit-monitord -e IKEA_USER=ikea_hub_user -e IKEA_HUB_ADDR=ikea_hub_ip -e IKEA_TOKEN=ikea_hub_token -e HOMEKIT_HUBS="10.10.10.20:200 10.10.10.30:200 10.10.10.40:200" -e NOTIFY_EMAIL="me@example.com" -e EMAIL_SENDER="bot@example.com" -e EMAIL_SERVER="smtp.example.com" -e EMAIL_PORT="587" -e EMAIL_PASSWORD="secret" -e RESTART_HUB=1 -e TELEGRAM_TOKEN=secret -e TELEGRAM_CHATID=chatid -d -p 8080:80 homekit-monitord:prod

  wait-container-start:
    runs-on: self-hosted
    environment: 'dev'
    needs: build-container
    steps:
    - name: "[wait-container-start] Wait for the container to fully start"
      run: sleep 30s
      shell: bash

  test-nginx:
    runs-on: self-hosted
    environment: 'dev'
    needs: wait-container-start
    steps:
    - name: "[test-nginx] Test if the container can receive healthchecks"
      run: curl --fail http://localhost:8080/active-hub-report-health/

  test-monit:
    runs-on: self-hosted
    environment: 'dev'
    needs: wait-container-start
    steps:
    - name: "[test-monit] Test if monit has started"
      run: docker exec homekit-monitord pgrep monit

  cleanup:
    runs-on: self-hosted
    environment: 'dev'
    needs: [test-nginx, test-monit, build-container]
    if: always()
    steps:
    - name: "[cleanup] Delete old images"
      run: docker rm -f homekit-monitord && docker rmi -f homekit-monitord:prod nginx; exit 0
    
  publish:
    runs-on: self-hosted
    environment: 'prod'
    needs: [test-nginx, test-monit]
    steps:
    - name: "[publish] Checkout code"
      uses: actions/checkout@v2
    - name: "[publish] Login to docker hub"
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: "[publish] Install buildx"
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
    - name: "[publish] Build and push the image"
      run: |
        docker buildx build --push \
          --tag clickbg/homekit-monitord:latest \
          --platform linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/amd64 .
