name: "Production"

on:
  push:
    branches: main
      
jobs:

  setup:
    runs-on: self-hosted
    environment: 'dev'
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2

  build:
    runs-on: self-hosted
    environment: 'dev'
    needs: setup
    steps:
      - id: build
      - uses: clickbg/build-container@v1

  run:
    runs-on: self-hosted
    environment: 'dev'
    needs: build
    steps:
      - id: run-all-opts
      - uses: clickbg/run-container-all-opts@v1
        with:
          build-id: ${{ steps.build.outputs.build-id }}

  test:
    runs-on: self-hosted
    environment: 'dev'
    needs: [build, run]
    steps:
      - uses: clickbg/test-monit@v1
        with:
          build-id: ${{ steps.build.outputs.build-id }}
      - uses: clickbg/test-nginx@v1
        with:
          port: ${{ steps.run-all-opts.outputs.port }}

  cleanup:
    runs-on: self-hosted
    environment: 'dev'
    needs: [build, run]
    if: always()
    steps:
      - uses: clickbg/cleanup@v1
        with: 
          build-id: ${{ steps.build.outputs.build-id }}

