name: "Production"

on:
  push:
    branches: main
      
jobs:

  setup:
    runs-on: self-hosted
    environment: 'dev'
    steps:
      - uses: actions/checkout@v2
        name: "Checkout code"

  build:
    runs-on: self-hosted
    environment: 'dev'
    needs: setup
    steps:
      - uses: clickbg/tests/build-container@v1
        id: build

  run:
    runs-on: self-hosted
    environment: 'dev'
    needs: build
    steps:
      - uses: clickbg/tests/run-container-all-opts@v1
        id: run-all-opts
        with:
          build-id: ${{ steps.build.outputs.build-id }}

  test:
    runs-on: self-hosted
    environment: 'dev'
    needs: [build, run]
    steps:
      - uses: clickbg/tests/test-monit@v1
        with:
          build-id: ${{ steps.build.outputs.build-id }}
      - uses: clickbg/tests/test-nginx@v1
        with:
          port: ${{ steps.run-all-opts.outputs.port }}

  cleanup:
    runs-on: self-hosted
    environment: 'dev'
    needs: [build, run, test]
    if: always()
    steps:
      - uses: clickbg/tests/cleanup@v1
        with: 
          build-id: ${{ steps.build.outputs.build-id }}

