name: "Production"

on:
  push:
    branches: main
      
jobs:

  setup:
    runs-on: self-hosted
    environment: 'dev'
    steps:
      - uses: actions/checkout@v2
        name: "Checkout code"

  build:
    runs-on: self-hosted
    environment: 'dev'
    needs: setup
    steps:
      - uses: ./.github/actions/build-container
        id: build

  run:
    runs-on: self-hosted
    environment: 'dev'
    needs: build
    steps:
      - uses: ./.github/actions/run-container-all-opts
        id: run-all-opts
        with:
          build-id: ${{ steps.build.outputs.build-id }}
      - uses: ./.github/actions/wait

  test:
    runs-on: self-hosted
    environment: 'dev'
    needs: [build, run]
    steps:
      - uses: ./.github/actions/tests/test-monit
        with:
          build-id: ${{ steps.build.outputs.build-id }}
      - uses: ./.github/actions/tests/test-nginx
        with:
          port: ${{ steps.run-all-opts.outputs.port }}

  cleanup:
    runs-on: self-hosted
    environment: 'dev'
    needs: [build, run, test]
    if: always()
    steps:
      - uses: ./.github/actions/cleanup
        with: 
          build-id: ${{ steps.build.outputs.build-id }}

