on:
  push:
    branches: main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the image
      run: |
        docker buildx build --push \
          --tag clickbg/homekit-monitord:latest \
          --platform linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/amd64 .
