name: "PUBLISH"
on:
  workflow_run:
    workflows: ["CICD"]
    types:
      - completed
    branches:
        - 'main'

  publish:
    runs-on: self-hosted
    environment: 'prod'
    needs: [test-nginx, test-monit]
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v2
    - name: "Delete old images"
      run: docker rmi -f homekit-monitord nginx; exit 0
    - name: "Login to docker hub"
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: "Install buildx"
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
    - name: "Build and push the image"
      run: |
        docker buildx build --push \
          --tag clickbg/homekit-monitord:latest \
          --platform linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/amd64 .
