name: "UPDATE"

on:
  schedule:
    - cron: "0 13 * * 1"
  workflow_dispatch:

jobs:

  update-check:
    runs-on: self-hosted
    environment: 'dev'
    outputs:
      image-needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
    - name: Docker Image Update Checker
      id: check
      uses: lucacome/docker-image-update-checker@v1
      with:
        base-image: library/nginx:latest
        image: clickbg/homekit-monitord:latest

  cicd:
    needs: update-check
    uses: clickbg/homekit-monitord/.github/workflows/cicd.yaml@main

  publish:
    needs: cicd
    uses: clickbg/homekit-monitord/.github/workflows/publish.yaml@main
