name: "UPDATE"

on:
  schedule:
    - cron: "0 13 * * 1"
  workflow_dispatch:

jobs:

  update-check:
    runs-on: self-hosted
    environment: 'dev'
    outputs:
      image-needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
    - name: Docker Image Update Checker
      id: check
      uses: lucacome/docker-image-update-checker@v1
      with:
        base-image: library/nginx:latest
        image: clickbg/homekit-monitord:latest

  cicd:
    needs: update-check
    runs-on: self-hosted
    environment: 'dev'
    steps:
      - uses: actions/checkout@v2
        name: "Checkout code"
      - uses: ./.github/workflows/cicd.yaml
        name: "Start the CICD pipeline if update is needed"
